Feat: Add to get orders from mktplace back-api
mousehaunt/mousehaunt.com pull request #249
Opened 2022-02-07 16:14 UTC by juo-dev

2022-02-07 18:06 UTC, pedrohw12 commented on utils/http.ts
> +export function isSuccessfulHttpRequest<T extends Error>(
Um mínimo detalhe de 1 letra - isSuccessFullHttpRequest

2022-02-07 18:14 UTC, pedrohw12 commented on types/api/marketplace/JsonMouse.ts
> +/* eslint-disable camelcase */
O backend retorna as variáveis em snake_case, mas no front geralmente usamos camelCase. 

Talvez pudéssemos manter em camelCase (incluindo aí nos types) e criar uma função helper para tratar os termos que vem do backend em snake_case para camelCase.

2022-02-07 18:18 UTC, pedrohw12 commented on repository/MarkeplaceRepository.ts
> +        const result: Order[] = data.results.map((booster: Booster) => {
Aqui já seria um bom lugar para se beneficiar de uma função helper que convertesse os valores de snake_case para camelCase.

2022-02-07 18:18 UTC, pedrohw12 commented on repository/MarkeplaceRepository.ts
> +import { BigNumber, ethers } from 'ethers'
O nome do arquivo ficou como 'MarkeplaceRepository'.

2022-02-07 18:25 UTC, pedrohw12 commented on pages/marketplace/orders/index.tsx
> +import React, { useEffect, useState } from 'react'
Acho que boa parte deste arquivo não faz mais sentido ou nem existe mais, já que vai deixar de existir a estrutura que fiz, não ?

2022-02-07 18:27 UTC, pedrohw12 commented on domain/usecases/load-orders.ts
> +export interface LoadOrders {
Esse arquivo não vai ser deletado por conta da mudança na arquitetura?

2022-02-07 18:28 UTC, pedrohw12 commented on data/usecases/remote-load-orders.ts
> +/* eslint-disable import/export */
Este arquivo não vai ser deletado?

2022-02-07 18:28 UTC, pedrohw12 commented on domain/usecases/index.ts
> -export * from './load-mouse'
Este arquivo não vai ser deletado?

2022-02-07 18:32 UTC, pedrohw12 commented on api/MarketplaceApi.ts
> +      if (error instanceof HttpException) throw error
Teria alguma forma de englobar esta lógica de tratativa de erro e só sair usando ela dentro dos catch? Pergunto isso porque vi em outros arquivos as mesmas linhas de código verificando a instancia do erro e retornando um erro ou um erro customizado.

2022-02-07 19:23 UTC, karacurt requested changes
Excelente trabalho! 🚀  Ficou bem mais limpo os contexts para dar getOders!! Fiz algumas sugestões de código e também pedi pra mudar aquele hardcode do `Web3Context` para poder funcionar na url de develop.

2022-02-07 19:23 UTC, karacurt commented on pages/marketplace/orders/index.tsx
> +import React, { useEffect, useState } from 'react'
Concordo, acho que podemos remover para não ficar código morto

2022-02-07 19:23 UTC, karacurt commented on pages/marketplace/orders/index.tsx
> +      ()
Remover essas lógicas não utilizadas por enquanto e depois voltamos quando tentarmos conectar os conceitos

2022-02-07 19:23 UTC, karacurt commented on repository/AssetRepository.ts
> +  getAssetList(): Asset[] {
Uma outra ideia: pedir pra api retornar isso pra gente. Criar como task a ser feita lá no backend futuramente

2022-02-07 19:23 UTC, karacurt commented on repository/AssetRepository.ts
> +  getAssetMouseHaunt() {
Outra sugestão: `getAcceptedToken()` pra dar match com a nomeclatura do contrato

2022-02-07 19:23 UTC, karacurt commented on types/api/marketplace/JsonBooster.ts
> +export type JsonBooster = {
```suggestion
export type JsonBoosterResponse = {
```

2022-02-07 19:23 UTC, karacurt commented on types/api/marketplace/JsonBooster.ts
> +export type Booster = {
```suggestion
export type BoosterResponse = {
```

2022-02-07 19:23 UTC, karacurt commented on types/api/marketplace/JsonMouse.ts
> +export type Mouse = {
```suggestion
export type MouseResponse = {
```

2022-02-07 19:23 UTC, karacurt commented on types/api/marketplace/JsonMouse.ts
> +export type JsonMouse = {
```suggestion
export type JsonMouseResponse = {
```

2022-02-07 19:23 UTC, karacurt commented on utils/http.ts
> +      throw new GenericException('403: Forbidden')
Tem um pacote legal que também faz essa questão de tratamento de erros: 
(é mais para estudo mesmo, para caso a gente queira alterar algo futuramente) 
https://www.npmjs.com/package/http-errors

2022-02-09 19:39 UTC, pedrohw12 approved these changes

2022-02-09 20:04 UTC, karacurt requested changes
Parece tudo ok. Só precisa arrumar a questão do `DEFAULT_NETWORK`

2022-02-09 20:04 UTC, karacurt commented on contexts/Web3Context.tsx
> +const DEFAULT_NETWORK = { NAME: 'bsc', CHAIN_ID: 56 }
precisa descomentar a testnet e comentar a mainet pra gente poder usar na url develop.mousehaunt.com
```suggestion
const DEFAULT_NETWORK = { NAME: 'bscTestnet', CHAIN_ID: 97 }
//const DEFAULT_NETWORK = { NAME: 'bsc', CHAIN_ID: 56 }
```

2022-02-09 20:28 UTC, merged