Context Api
mousehaunt/mousehaunt.com pull request #25
Opened 2022-01-03 12:36 UTC by rsaggio

Opa Ântonio, segue o código no status que estava ontem quando apresentei, qualquer alteração só comentar aqui nesse PR.

Obrigado,

2022-01-03 21:50 UTC, karacurt requested changes
Alguns outros detalhes que ficou de fora mas que pareceram desalinhados na questão do visual. 

Footer:

<img width="1439" alt="Screen Shot 2022-01-03 at 17 55 18" src="https://user-images.githubusercontent.com/38267570/147984184-6b0cf7eb-6fec-46b5-b846-f6b6f262e1bb.png">

Mobile:

<img width="419" alt="Screen Shot 2022-01-03 at 17 03 27" src="https://user-images.githubusercontent.com/38267570/147984214-ad4893b6-c71d-4610-b8cd-561b9ceb1319.png">

2022-01-03 21:50 UTC, karacurt commented on components/common/TableOrderDetails/index.tsx
> +      </table>
Precisa Alinhar essa parte
<img width="1146" alt="Screen Shot 2022-01-03 at 17 59 16" src="https://user-images.githubusercontent.com/38267570/147979834-8e889f67-0442-42bd-a45f-e4cb08de7f9f.png">

2022-01-03 21:50 UTC, karacurt commented on components/common/TrendingProduct/index.tsx
> +                <CardShop/>
trocar a lógica para se repetir a partir de um array. Esses cards não deveriam receber variáveis das informações como parâmetro?

2022-01-03 21:50 UTC, karacurt commented on components/common/TrendingProduct/styles.tsx
> +  margin: auto;
O rolar para o lado nao esta funcionando
<img width="1411" alt="Screen Shot 2022-01-03 at 18 06 01" src="https://user-images.githubusercontent.com/38267570/147980458-7565dbe9-f48d-45be-9b4d-a7776075cee2.png">

2022-01-03 21:50 UTC, karacurt commented on pages/createOrder/formCreateOrder.tsx
> +        <FormContent>
É preciso um campo para quantidade como amount. Além disso, quando algum produto é selecionado para criar a oferta ele é totalmente apagado pelo rosa
<img width="1123" alt="Screen Shot 2022-01-03 at 18 30 18" src="https://user-images.githubusercontent.com/38267570/147982619-12907f72-0337-40b1-9462-794cc7033d70.png">

2022-01-03 21:50 UTC, karacurt commented on pages/createOrder/index.tsx
> +        </Container>
Não está centralizado
<img width="1440" alt="Screen Shot 2022-01-03 at 18 33 02" src="https://user-images.githubusercontent.com/38267570/147982748-bf8c18be-8813-42a0-8c2e-3e8789c9d9e9.png">

2022-01-03 21:50 UTC, karacurt commented on pages/index.tsx
> +        {/*<PhishingBanner />*/}
Pode descomentar precisamos como vai ficar o visual com o banner

2022-01-03 21:50 UTC, karacurt commented on pages/marketplace/index.tsx
> +        console.log('passei no load more')
remover logs

2022-01-03 21:50 UTC, karacurt commented on pages/orderDetails/index.tsx
> +                        <TrendingProduct/>
OrderActivity e TrendingProduct estão desalinhados e o espaçamento dos cards do trending parece diferente da index (esta mais espaçada na index).
<img width="1432" alt="Screen Shot 2022-01-03 at 18 42 26" src="https://user-images.githubusercontent.com/38267570/147983744-a7972137-07ac-4b53-b95a-a99f6097a608.png">

2022-01-03 21:58 UTC, karacurt commented on components/common/CardSuccess/index.tsx
> +};
@aviggiano

2022-01-03 21:58 UTC, karacurt commented on components/common/CardCreateOrder/index.tsx
> +        </Card>
@aviggiano

2022-01-03 21:58 UTC, karacurt commented on components/common/FilterMarketplace/FilterDefault.tsx
> +                            <ClearText onClick={clear}>Clear All</ClearText>
@aviggiano

2022-01-03 21:58 UTC, karacurt commented on components/common/PopularCollection/index.tsx
> +            <ContainerBody>
@aviggiano

2022-01-03 21:58 UTC, karacurt commented on components/common/SelectPrices/index.tsx
> +            <option value="4">$MHT</option>
@aviggiano

2022-01-03 21:59 UTC, karacurt commented on components/common/TableOrderDetails/index.tsx
> +      </table>
@aviggiano

2022-01-03 21:59 UTC, karacurt commented on components/common/TrendingProduct/index.tsx
> +                <CardShop/>
@aviggiano

2022-01-03 21:59 UTC, karacurt commented on components/common/TrendingProduct/styles.tsx
> +  margin: auto;
@aviggiano

2022-01-03 21:59 UTC, karacurt commented on pages/createOrder/formCreateOrder.tsx
> +        <FormContent>
@aviggiano

2022-01-03 22:00 UTC, karacurt commented on pages/createOrder/index.tsx
> +        </Container>
@aviggiano

2022-01-03 22:00 UTC, karacurt commented on pages/orderDetails/index.tsx
> +                        <TrendingProduct/>
@aviggiano

2022-01-03 22:23 UTC, aviggiano commented on components/common/CardCollection/index.tsx
> +                    <Subtitle>Owner: <b>Name Surname</b></Subtitle>
**Vou fazer esse**

2022-01-03 22:24 UTC, aviggiano commented on components/common/CardCreateOrder/index.tsx
> +        </Card>
**Vou fazer esse**

2022-01-03 22:24 UTC, aviggiano commented on components/common/CardShop/index.tsx
> +                            posted 3 days ago
**Vou fazer esse**

2022-01-03 22:24 UTC, aviggiano commented on components/common/CardSuccess/index.tsx
> +};
**Vou fazer esse**

2022-01-03 22:24 UTC, aviggiano commented on components/common/SelectPrices/index.tsx
> +            <option value="4">$MHT</option>
**Vou fazer esse**

2022-01-03 22:25 UTC, aviggiano commented on components/common/TrendingProduct/index.tsx
> +                <CardShop/>
**Vou fazer esse**

2022-01-03 22:25 UTC, aviggiano commented
@rsaggio podem priorizar as questões visuais levantadas pelo @karacurt por favor? 
Tudo aquilo que estiver indicado como **Vou fazer esse**, significa que eu vou ajustar no meu merge.
O restante pode seguir a revisão dele!

2022-01-05 18:52 UTC, karacurt commented
Ainda falta alguns detalhes da rolagem dos cards na pagina inicial e alguns alinhamentos que ja foram marcados aqui no PR. Surgiram mais duas coisas:
- Na tela de create order, adicionar rolagem na seção type, futuramente será adicionado mais "ButtonsNFT" e no esquema atual ele quebra o layout. 
- Na tela de order details não tem mobile view configurada. 

![Captura de Tela (12)](https://user-images.githubusercontent.com/38267570/148272524-1f94d12d-9387-419a-9a97-a2ec387006fe.png)
![Captura de Tela (11)](https://user-images.githubusercontent.com/38267570/148272527-dc05ace4-3e13-49f0-b5f2-76f0a6f15028.png)

2022-01-05 19:17 UTC, karacurt requested changes
Foi um bom progresso, acredito que a agora é preciso se concentrar mais nos detalhes da visão mobile

2022-01-05 19:17 UTC, karacurt commented on filters/AssetIdFilter.tsx
> +export const AssetIdFilter = () =>  {
`AssetIdFilter: React.FC = () => {`

2022-01-05 19:17 UTC, karacurt commented on filters/IdFilter.tsx
> +export const IdFilter = () =>  {
`export const IdFilter: React.FC = () => {`

2022-01-05 19:17 UTC, karacurt commented on filters/RarityFilter.tsx
> +export const RarityFilter = () =>  {
idem anteriores

2022-01-05 19:17 UTC, karacurt commented on pages/createOrder/formCreateOrder.tsx
> +                <Input placeholder="Amount" type="number"/>
os inputs do forms não estão sendo setados em variáveis; 

`onChange={(obj) => setAmount(obj.target.value)}`

2022-01-05 19:17 UTC, karacurt commented on pages/createOrder/index.tsx
> +                    </Mobile>
Componente sendo renderizado de forma duplicada. A visão web/mobile precisa ser modificada dentro do componente via styles. Renderizar de forma duplicada gera dados conflitantes quando muda de um para o outro, precisamos mudar principalmente quando formos usar as variáveis de input dos forms para enviar para os contexts .

2022-01-07 23:29 UTC, aviggiano commented
Boa noite pessoal

Registro aqui o aceite formal do projeto. 

Fizemos o merge com sucesso do front com a blockchain em outra branch e já foi possível usar a testnet para validar todas as funcionalidades principais.

Entro em contato por WhatsApp para realizarmos o pagamento.

Att

2022-01-07 23:30 UTC, closed without merging