Feature/pagination
mousehaunt/mousehaunt.com pull request #41
Opened 2022-01-07 18:09 UTC by karacurt

Just fixed the actual logic, we change to something more fancy later

2022-01-07 23:25 UTC, aviggiano requested changes

2022-01-07 23:25 UTC, aviggiano commented on pages/marketplace/explore.tsx
> -                {filteredOrders.map((order) => (
Here it's filteredOrders I think

Because you must apply the filters to the results, and orders is what we get from the blockchain directly

2022-01-07 23:27 UTC, karacurt commented on pages/marketplace/explore.tsx
> -                {filteredOrders.map((order) => (
this is a local order only for this component `setOrders(filteredOrders.slice(0, page*productsPerPage))`

2022-01-08 23:52 UTC, aviggiano commented on pages/marketplace/explore.tsx
> -                {filteredOrders.map((order) => (
OHH ok

2022-01-08 23:52 UTC, aviggiano approved these changes

2022-01-08 23:53 UTC, aviggiano commented
Lint is not passing

2022-01-10 00:39 UTC, merged